---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[rbenv::default]
    attributes:
      rbenv:
        user: rbenv
        group: rbenv
        rubies:
          - 2.1.0
        gems:
          2.1.0: 
            - bundler
